config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/bienvenue/:first_name', to: 'static_pages#bienvenue', as: 'bienvenue'
  resources :users
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users

	validates :name,
		presence: true
	validates :zip_code
		presence: true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content,
		presence: true

	belongs_to :user
	belongs_to :gossip
	has_many :likes, as: :likeable
	belongs_to :commentable, polymorphic: true, optional: true
	has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments
	has_many :likes, as: :likeable

	validates :title,
		presence: true,
		length: { in: 3..14 }
	validates :content,
	  presence: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/join_table_pm_recipient.rb
class JoinTablePmRecipient < ApplicationRecord
	belongs_to :received_message, class_name: "PrivateMessage"
	belongs_to :recipient, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	validates :content,
		presence: true

	belongs_to :sender, class_name: "User"
	has_many :join_table_pm_recipients, foreign_key: 'received_message_id', class_name: "JoinTablePmRecipient"
	has_many :recipients, through: :join_table_pm_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title,
		presence: true,
		length: {in: 2..140}

	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name,
		presence: true,
		length: { minimum: 2 }
	validates :last_name,
		presence: true,
		length: { minimum: 2 }
	validates :description,
		length: { maximum: 500 }
	validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Email adress please" }
  validates :age,
  	presence: true,
  	numericality: { only_integer: true, greater_than: 18 }
  
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :join_table_pm_recipients, foreign_key: 'recipient_id', class_name: "JoinTablePmRecipient"
	has_many :received_messages, through: :join_table_pm_recipients
	has_many :comments
	has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
  	@gossip = Gossip.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
  	@gossip = Gossip.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def team
  end

  def bienvenue
  	@first_name = params[:first_name]
  end

  def home
  	@gossips = Gossip.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossip/show.html.erb
<h1>Gossip n° <%= @gossip.id %></h1>
<p>Gossip auteur <%= @gossip.user.first_name %><%= @gossip.user.last_name %></p>
<p>Voici sa page <%= link_to 'clique ici', user_show_path(@gossip.user) %></p>
<p>Gossip title <%= @gossip.title %></p>
<p>Gossip contenu <%= @gossip.content %></p>

app/views/gossips/show.html.erb
<h1>Gossip n° <%= @gossip.id %></h1>
<p>Gossip auteur <%= @gossip.user.first_name %><%= @gossip.user.last_name %></p>
<p>Voici sa page <%= link_to 'clique ici', user_path(@gossip.user) %></p>
<p>Gossip title <%= @gossip.title %></p>
<p>Gossip contenu <%= @gossip.content %></p>

app/views/static_pages/bienvenue.html.erb
<h1>Bienvenue <%= @first_name %></h1>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
<p>Voici notre équipe lol mdr 😇❤️😻</p>

app/views/static_pages/home.html.erb
<h1>Home Page de Gossip Project</h1>
<% @gossips.each do |gossip| %>
<p>Ceci est l'auteur : <%= gossip.user.first_name%></p>
<p>Ceci est le titre : <%= gossip.title%></p>
<p>Lien vers la page : <%= link_to "clique ici", gossip_path(gossip) %></p><br/><br/>
<% end %>

app/views/static_pages/team.html.erb
<h1>StaticPages#team</h1>
<p>Find me in app/views/static_pages/team.html.erb</p>

app/views/users/show.html.erb
<h1>User<%= @user.id %></h1>
<p>User prénom <%= @user.first_name %></p>
<p>User nom <%= @user.last_name %></p>
<p>User desc <%= @user.description %></p>
<p>User age <%= @user.age %></p>